### PR TITLE
WIP - Improve plugin 1

### PR DESCRIPTION
**Pull request by phil-lgr**
merge #2 first

I'm working on new features as discussed in #3 

image

### CODE REVIEW

**Comment by phil-lgr** [comment]
I've added React and cleaned up the ui code

**Comment by oriziv** [comment]
Just "Name Format" option need to be implemented i saw that its always lowercase

**Comment by phil-lgr** [comment]
Yes correct, I think I will have some time later this week, if you would like to have a go at it please merge this into master or a branch and have a look

When I stopped I was actually looking into this

**Comment by oriziv** [comment]
Merged

**Pull request merged**
